import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const safeUrl=value=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:'#';}catch{return '#';}};
export const slug=value=>String(value??'').toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');
export function paginate(records,size){return Array.from({length:Math.max(1,Math.ceil(records.length/size))},(_,i)=>records.slice(i*size,(i+1)*size));}
export function mergeSourceDirectory(runtimeSources,researchSources){
 const homepageKey=source=>{const url=safeUrl(source.website_url||source.url);return url==='#'?null:url;};
 const matched=new Set();
 const sources=runtimeSources.map(runtime=>{
  const id=runtime.source||runtime.id;const homepage=homepageKey(runtime);
  const researchMatches=researchSources.filter(candidate=>(id&&(candidate.id===id||candidate.adapter_source_id===id))||(homepage&&homepageKey(candidate)===homepage));
  const research=researchMatches.find(candidate=>candidate.name)||researchMatches[0];
  for(const candidate of researchMatches)matched.add(candidate);
  const descriptive={};
  for(const key of ['name','description','country','country_name','publisher_country','language','content_types','categories','coverage','operator','source_kind','verified_at','last_check_at','rights_status','rights_review_status','freshness_evidence','retrieval_notes'])if(research?.[key]!=null)descriptive[key]=research[key];
  return {...descriptive,...runtime,id:runtime.id||id,name:runtime.name||research?.name||id,description:runtime.description||research?.description||research?.freshness_evidence,
   acquisition_state:runtime.acquisition_state||runtime.status||'unknown',last_success_at:runtime.last_success_at??null,error:runtime.error??null};
 });
 return {sources,directory:[...sources,...researchSources.filter(candidate=>!matched.has(candidate))]};
}
export async function build(options={}){
const config={...JSON.parse(await fs.readFile(path.join(root,'site.config.json'),'utf8')),...(process.env.SITE_URL?{url:process.env.SITE_URL}:{}),...options.config};
config.url=config.url.replace(/\/$/,'');const basePath=new URL(config.url).pathname.replace(/\/$/,'');
const out=options.out||path.join(root,'dist'); await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});
let catalog={schema_version:1,opportunities:[],sources:[]};const input=options.input||process.env.CATALOG_PATH||path.join(root,'data/catalog.json');
try{catalog=JSON.parse(await fs.readFile(input,'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;if(process.env.REQUIRE_CATALOG==='1')throw new Error('A published catalog is required');}
if(![1,'1','1.0'].includes(catalog.schema_version))throw new Error('Unsupported catalog schema');
if(!Array.isArray(catalog.opportunities)||!Array.isArray(catalog.sources))throw new Error('Invalid catalog collections');
if(!Number.isInteger(config.pageSize)||config.pageSize<1)throw new Error('Invalid page size');
const ids=new Set();for(const r of catalog.opportunities){if(typeof r.id!=='string'||typeof r.title!=='string'||typeof r.url!=='string'||!Array.isArray(r.host_countries)||!Array.isArray(r.eligible_countries))throw new Error('Invalid opportunity record');if(!/^[a-zA-Z0-9-]+$/.test(r.id)||!r.title.trim()||typeof r.summary!=='string'||r.summary.length>600||!['scholarships','internships','volunteering','training','jobs','competitions','grants','fellowships','other'].includes(r.category)||!['open','expired','unknown'].includes(r.status)||safeUrl(r.url)==='#'||[...r.host_countries,...r.eligible_countries].some(c=>!/^([A-Z]{2})$/.test(c)))throw new Error('Malformed opportunity contract');for(const key of ['deadline','published_at','last_checked_at'])if(r[key]!=null&&(typeof r[key]!=='string'||!Number.isFinite(Date.parse(r[key]))))throw new Error('Invalid opportunity date');if(ids.has(slug(r.id))||!slug(r.id))throw new Error('Duplicate or unsafe record ID');ids.add(slug(r.id));}
const records=(catalog.opportunities||[]).filter(r=>r.status!=='expired');let research=[];try{research=Array.isArray(catalog.source_registry)?catalog.source_registry:JSON.parse(await fs.readFile(path.join(root,'data/source-registry.json'),'utf8')).sources||[];}catch{}const {sources,directory}=mergeSourceDirectory(catalog.sources||[],research);
let contributors=[];let contributorMeta={};try{const data=JSON.parse(await fs.readFile(path.join(root,'data/contributors.json'),'utf8'));contributorMeta=Array.isArray(data)?{}:data;contributors=Array.isArray(data)?data:data.contributors||[];}catch{}
const routes=[];const e=escapeHtml;const fallbackCategories=['scholarships','internships','volunteering','training','jobs','competitions','grants','fellowships','other'];
const taxonomy=Array.isArray(catalog.taxonomy?.categories)?catalog.taxonomy.categories.filter(c=>fallbackCategories.includes(c.id)&&typeof c.label==='string'):[];
const categories=[...new Set([...taxonomy.map(c=>c.id),...fallbackCategories])];
const recordCategories=r=>Array.isArray(r.categories)&&r.categories.length?r.categories.filter(c=>categories.includes(c)):[r.category];
const label=s=>taxonomy.find(c=>c.id===s)?.label||s.charAt(0).toUpperCase()+s.slice(1);const date=s=>s?e(String(s).slice(0,10)):'Not provided';
const countryName=code=>{try{return new Intl.DisplayNames(['en'],{type:'region'}).of(code)||code;}catch{return code;}};
const json=value=>JSON.stringify(value).replace(/</g,'\\u003c');
const navigation=[['/opportunities/','Explore'],['/sources/','Sources'],['/about/','Our mission'],['/docs/','Docs'],['/contributors/','Community']];
const header=(route)=>`<header class="site-header"><div class="wrap header-inner"><a class="brand" href="/"><img src="/assets/logo.svg" width="34" height="34" alt=""><span>YouthOpp</span></a><span class="brand-caption">Open opportunity index</span><nav aria-label="Main navigation">${navigation.map(([url,text])=>`<a href="${url}" ${route.startsWith(url)?'aria-current="page"':''}>${text}</a>`).join('')}</nav><a class="github-link" href="https://github.com/fmarslan/YouthOpp-youthopp.github.io">Contribute</a></div></header>`;
async function page(route,title,description,body,structured={}){
const canonical=config.url+route;
const organizationId=config.url+'/#organization';const websiteId=config.url+'/#website';
const crumbs=[{name:'Home',route:'/'}];
if(route!=='/'){
 if(route.startsWith('/docs/')&&route!=='/docs/')crumbs.push({name:'Docs',route:'/docs/'});
 else if(route.startsWith('/opportunity/')||route.startsWith('/countries/')||(route.startsWith('/opportunities/')&&route!=='/opportunities/'))crumbs.push({name:'Opportunities',route:'/opportunities/'});
 const category=categories.find(c=>route.startsWith(`/opportunities/${c}/`));
 if(category&&route!==`/opportunities/${category}/`)crumbs.push({name:label(category),route:`/opportunities/${category}/`});
 const pageNumber=route.match(/^(.*\/)page\/(\d+)\/$/);
 if(pageNumber&&!crumbs.some(c=>c.route===pageNumber[1]))crumbs.push({name:title,route:pageNumber[1]});
 crumbs.push({name:pageNumber?`Page ${pageNumber[2]}`:title,route});
}
const breadcrumb={'@type':'BreadcrumbList','@id':canonical+'#breadcrumbs',itemListElement:crumbs.map((c,index)=>({'@type':'ListItem',position:index+1,name:c.name,item:config.url+c.route}))};
const graph={'@context':'https://schema.org','@graph':[
 {'@type':'Organization','@id':organizationId,name:'YouthOpp',url:config.url+'/',description:'An independent open-source opportunity discovery project with a nonprofit purpose.',logo:config.url+'/assets/logo.svg',sameAs:['https://github.com/fmarslan/YouthOpp-youthopp.github.io']},
 {'@type':'WebSite','@id':websiteId,name:'YouthOpp',url:config.url+'/',publisher:{'@id':organizationId},inLanguage:'en'},
 {'@type':route.includes('/opportunities/')||route.startsWith('/countries/')||route==='/sources/'?'CollectionPage':'WebPage','@id':canonical+'#webpage',name:title,url:canonical,description,isPartOf:{'@id':websiteId},publisher:{'@id':organizationId},...(route!=='/'?{breadcrumb:{'@id':breadcrumb['@id']}}:{}),...structured},
 ...(route!=='/'?[breadcrumb]:[])
]};
let html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · YouthOpp</title><meta name="description" content="${e(description)}"><link rel="canonical" href="${e(canonical)}"><meta property="og:type" content="website"><meta property="og:site_name" content="YouthOpp"><meta property="og:title" content="${e(title)} · YouthOpp"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(config.url)}/assets/social-preview.png"><meta property="og:image:alt" content="YouthOpp — More opportunity. Less searching."><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${e(title)} · YouthOpp"><meta name="twitter:description" content="${e(description)}"><meta name="twitter:image" content="${e(config.url)}/assets/social-preview.png"><meta name="twitter:image:alt" content="YouthOpp — More opportunity. Less searching."><link rel="icon" href="/assets/logo.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css">${config.googleVerification?`<meta name="google-site-verification" content="${e(config.googleVerification)}">`:''}${config.bingVerification?`<meta name="msvalidate.01" content="${e(config.bingVerification)}">`:''}<script type="application/ld+json">${json(graph)}</script></head><body><a class="skip" href="#main">Skip to content</a>${header(route)}<main id="main">${body}</main><footer><div class="wrap footer-grid"><div><a class="brand" href="/">YouthOpp.</a><p>More opportunity. Less searching.</p><p class="small">Nonprofit purpose. Open source. Built with AI, shaped by people.</p></div><div><a href="/about/">About the project</a><a href="/docs/contributing/">Contribute</a><a href="/docs/privacy/">Privacy & source policy</a><a href="https://github.com/fmarslan/YouthOpp-youthopp.github.io">GitHub ↗</a></div></div><div class="wrap small footer-note">Always check dates, eligibility and application details with the original publisher. YouthOpp is an independent index, not the opportunity provider.</div></footer>${/^G-[A-Z0-9]+$/.test(config.googleAnalyticsId||'')?`<script src="/assets/analytics.js" data-id="${e(config.googleAnalyticsId)}" data-base="${e(basePath)}" defer></script>`:''}<script src="/assets/index.js" defer></script></body></html>`;
html=html.replace(/(href|src)="\/(?!\/)/g,`$1="${e(basePath)}/`);
const dest=path.join(out,route,'index.html');await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,html);routes.push(route);
}
const sourceName=r=>sources.find(s=>(s.id||s.source)===r.source)?.name||r.source||'Original source';
const kindDefinitions={
 'programme-overview':{label:'Programme overview',note:'Programme information. Confirm current application calls and dates with the publisher.',action:'View programme information ↗'},
 'institutional-grant':{label:'Institutional grant',note:'Funding for institutions or organisations. Confirm eligible applicants and current calls with the publisher.',action:'View institutional grant details ↗'}
};
const recordKinds=r=>{
 const kinds=['opportunity','programme-overview','institutional-grant','unknown'].includes(r.kind)?[r.kind]:(Array.isArray(r.tags)?r.tags:[]);
 return kinds.filter(kind=>Object.hasOwn(kindDefinitions,kind)).map(kind=>kindDefinitions[kind]);
};
const kindNotice=r=>recordKinds(r).map(kind=>`<p class="small"><span class="tag">${e(kind.label)}</span> ${e(kind.note)}</p>`).join('');
const detailAction=r=>recordKinds(r)[0]?.action||'Read the original & apply ↗';
const detailDescription=r=>r.summary.trim()||recordKinds(r)[0]?.note||'Original-source opportunity information. Confirm dates, eligibility and application details with the publisher.';
const row=r=>`<tr class="opportunity" data-category="${e(r.category)}" data-countries="${e(r.host_countries.join(' '))}"><td><a class="row-title" lang="${e(r.language||'und')}" href="/opportunity/${slug(r.id)}/">${e(r.title)}</a><span class="row-category">${e(label(r.category))}${recordKinds(r).map(kind=>` · <span class="tag">${e(kind.label)}</span><span class="sr-only"> ${e(kind.note)}</span>`).join('')}</span></td><td><a class="row-source" href="${e(safeUrl(r.url))}" rel="noopener noreferrer">${e(sourceName(r))}<span aria-hidden="true"> ↗</span><span class="sr-only"> — original source</span></a></td><td>${r.host_countries.length?e(r.host_countries.map(countryName).join(', ')):'Not provided'}</td></tr>`;
const rows=items=>`<div class="index-table"><table><caption class="sr-only">Opportunities with original sources and destinations</caption><thead><tr><th scope="col">Opportunity</th><th scope="col">Source</th><th scope="col">Country</th></tr></thead><tbody>${items.map(row).join('')}</tbody></table></div>`;
const controls=(items,scope)=>`<form class="index-search" role="search"><div class="search-field"><label class="sr-only" for="index-query">Search ${scope}</label><input id="index-query" name="q" type="search" placeholder="Search ${scope}…"></div><div><label class="sr-only" for="index-country">Destination country</label><select id="index-country" name="country"><option value="">All countries</option>${[...new Set(items.flatMap(r=>r.host_countries))].sort().map(c=>`<option value="${c}">${e(countryName(c))}</option>`).join('')}<option value="unknown">Location not provided</option></select></div><button class="button" type="submit">Search</button></form><p class="search-note">Search and country filter apply to ${scope}. Eligibility must be checked with the publisher.</p><p class="filter-status small" role="status" aria-live="polite"></p><p class="no-results" hidden>No matching opportunities. Try another search or browse the full index.</p>`;
const empty=`<div class="empty"><h2>The catalog is being prepared</h2><p>We do not publish sample opportunities as real listings. Visit our source directory or help connect a trusted source.</p><a class="button" href="/sources/">Explore sources ↗</a></div>`;
const latest=records.slice(0,12);
const collectionLabel=s=>({ok:'Collection healthy',error:'Collection needs attention',stale:'Collection may be out of date',partial:'Partial collection'}[s.acquisition_state||s.status]||'Collection status unknown');
const contributorPreview=[...contributors].sort((a,b)=>b.score-a.score||a.login.localeCompare(b.login)).slice(0,3);
await page('/','Find your next opportunity',config.description,`<section class="wrap home-intro"><h1>Find your next opportunity.</h1><p>Scholarships, internships and programmes. Independent sources, one shared index.</p>${controls(latest,'the latest listings')}<nav class="category-tabs" aria-label="Opportunity categories"><a aria-current="page" href="/opportunities/">All</a>${categories.filter(c=>c!=='other').map(c=>`<a href="/opportunities/${c}/">${label(c)}</a>`).join('')}</nav></section><section class="wrap home-directory"><div class="directory-main"><div class="section-heading"><h2>Latest opportunities</h2><span class="small">Recently indexed · ${latest.length} listings</span></div>${latest.length?rows(latest):empty}<a class="index-more" href="/opportunities/">Explore all opportunities →</a></div><aside class="directory-aside"><h2>Source directory</h2><p>Explore organisations that publish opportunities for young people.</p><div class="publisher-list">${sources.slice(0,4).map(s=>`<div><a href="${e(safeUrl(s.website_url||s.url))}">${e(s.name)}</a><p>${e(s.country&&/^[A-Z]{2}$/.test(s.country)?countryName(s.country):'International')} · ${e(collectionLabel(s))}</p></div>`).join('')}</div><a href="/sources/">Explore all sources →</a><div class="community-panel"><p class="eyebrow">COMMUNITY</p><h2>Built together.</h2><p>Discover a source. Improve the index. Share your skills.</p><a class="button outline" href="/docs/contributing/">Get involved</a></div></aside></section><section class="wrap people-strip"><div><h2>People make the index.</h2><p>Open contributions. Transparent recognition.</p><a href="/contributors/">Meet the community →</a></div>${contributorPreview.map(c=>`<a class="person-preview" href="${e(safeUrl(c.html_url||`https://github.com/${c.login}`))}"><span class="person-monogram" aria-hidden="true">${e((c.name||c.login).slice(0,2).toUpperCase())}</span><span><strong>${e(c.name||c.login)}</strong><span>${e(c.score)} contribution ${c.score===1?'point':'points'}</span></span></a>`).join('')}</section>`);
async function listing(base,title,items){const selectedCategory=categories.find(c=>base.startsWith(`/opportunities/${c}/`));const countryBase=selectedCategory?`/opportunities/${selectedCategory}/`:'/countries/';const chunks=paginate(items,config.pageSize);for(let i=0;i<chunks.length;i++){const route=i===0?base:`${base}page/${i+1}/`;await page(route,title,`Explore ${title.toLowerCase()} with original publisher links.`,`<section class="wrap section"><p class="eyebrow">EXPLORE THE INDEX</p><h1 class="page-title">${e(title)}</h1><p class="lede">Short summaries. Original sources. Your next step.</p><div class="catalog-layout"><aside class="filters"><h2>Browse by category</h2><a href="/opportunities/">All opportunities</a>${categories.map(c=>`<a href="/opportunities/${c}/">${label(c)}</a>`).join('')}<h2>Browse by destination</h2>${[...new Set((selectedCategory?records.filter(r=>recordCategories(r).includes(selectedCategory)):records).flatMap(r=>r.host_countries||[]))].sort().map(c=>`<a href="${countryBase}${slug(c)}/">${e(countryName(c))}</a>`).join('')}<a href="${countryBase}unknown/">Location not provided</a><p class="small">Destination is where the opportunity takes place. It does not establish who may apply.</p></aside><div><div class="result-bar"><strong>${items.length} opportunities</strong><span>Page ${i+1} of ${chunks.length}</span></div>${controls(chunks[i],'this page')}${chunks[i].length?rows(chunks[i]):empty}<nav class="pagination" aria-label="Catalog pages">${chunks.map((_,j)=>`<a ${j===i?'aria-current="page"':''} href="${j===0?base:`${base}page/${j+1}/`}">${j+1}</a>`).join('')}</nav></div></div></section>`);}}
await listing('/opportunities/','All opportunities',records);for(const c of categories)await listing(`/opportunities/${c}/`,label(c),records.filter(r=>recordCategories(r).includes(c)));for(const c of [...new Set(records.flatMap(r=>r.host_countries||[]))])await listing(`/countries/${slug(c)}/`,countryName(c),records.filter(r=>(r.host_countries||[]).includes(c)));await listing('/countries/unknown/','Location not provided',records.filter(r=>!(r.host_countries||[]).length));
for(const c of categories){const categoryRecords=records.filter(r=>recordCategories(r).includes(c));for(const country of [...new Set(categoryRecords.flatMap(r=>r.host_countries||[]))])await listing(`/opportunities/${c}/${slug(country)}/`,`${label(c)} in ${countryName(country)}`,categoryRecords.filter(r=>r.host_countries.includes(country)));await listing(`/opportunities/${c}/unknown/`,`${label(c)} — location not provided`,categoryRecords.filter(r=>!r.host_countries.length));}

for(const r of records)await page(`/opportunity/${slug(r.id)}/`,r.title,detailDescription(r),`<section class="wrap section narrow"><a class="text-link" href="/opportunities/">← Back to opportunities</a><p class="eyebrow">${e(label(r.category||'other'))}</p><h1 class="page-title" lang="${e(r.language||'und')}">${e(r.title)}</h1><p class="lede" lang="${e(r.language||'und')}">${e(r.summary)}</p>${kindNotice(r)}<dl class="detail-grid"><dt>Destination</dt><dd>${(r.host_countries||[]).length?e(r.host_countries.map(countryName).join(', ')):'Not provided'}</dd><dt>Who may apply</dt><dd>${(r.eligible_countries||[]).length?e(r.eligible_countries.map(countryName).join(', ')):'Not provided — check the source'}</dd><dt>Deadline</dt><dd>${date(r.deadline)}</dd><dt>Last checked</dt><dd>${date(r.last_checked_at)}</dd><dt>Publisher</dt><dd>${e(sourceName(r))}</dd></dl><a class="button" href="${e(safeUrl(r.url))}">${e(detailAction(r))}</a><p class="notice">This is a discovery summary. A recent collection does not guarantee that applications remain open. Confirm all information with the publisher.</p></section>`);
await page('/sources/','Source directory','The original publishers behind the YouthOpp opportunity index.',`<section class="wrap section"><p class="eyebrow">FOLLOW THE ORIGINAL</p><h1 class="page-title">A world of sources.</h1><p class="lede">Credit belongs to the publishers. Explore our sources and how we collect their information.</p><div class="source-grid">${directory.length?directory.map(s=>`<article class="source-card"><span class="tag">${e((s.publisher_country||s.country)&&/^[A-Z]{2}$/.test(s.publisher_country||s.country)?countryName(s.publisher_country||s.country):'International')}</span><h2>${e(s.name)}</h2><p>${e(s.description||s.coverage||'Opportunity publisher')}</p><p class="small">Language: ${e(s.language||'Not provided')} · Method: ${e(s.retrieval_method||s.retrieval?.method||s.adapter||s.method||'See source register')}</p><p class="small">Source status: ${e(s.acquisition_state||s.status||'See source register')} · Last collection success: ${date(s.last_success_at)}</p>${s.error?`<p class="small">Latest collection error: ${e(s.error)}</p>`:''}<p class="small">Content: ${e((s.categories||s.content_types||[]).map(label).join(', ')||'See register')} · Last reviewed/checked: ${date(s.verified_at||s.last_check_at)}</p><p class="small">Reuse: ${e(s.rights_review_status||'Pending source-specific review')}</p><a href="${e(safeUrl(s.website_url||s.url))}">Visit publisher ↗</a></article>`).join(''):'<p>No published source register is connected yet.</p>'}</div><p><a href="/docs/source-research/">Read the research & source register →</a></p></section>`);
await page('/about/','Our mission','An open, nonprofit-purpose opportunity index and a place to learn AI through meaningful contributions.',`<section class="wrap section narrow"><p class="eyebrow">WHY WE EXIST</p><h1 class="page-title">Opportunity should be easier to find.</h1><p class="lede">Good opportunities are scattered across regions, languages and websites. YouthOpp brings discovery into one place, then sends you to the original source.</p><div class="prose"><h2>For students, young people and recent graduates</h2><p>Our purpose is to reduce the effort of finding scholarships, internships, learning experiences and first career steps. We index brief summaries; publishers remain the authority on eligibility and applications.</p><h2>Nonprofit purpose, public work</h2><p>YouthOpp is an open-source project built for public benefit. This describes our mission, not a claim of registered charitable status. We welcome contributions and support from people and institutions who share that purpose.</p><h2>AI-built, human-accountable</h2><p>The project idea, development and ongoing coordination use AI agents under human direction. AI participation is disclosed in commits, pull requests and project records. People remain responsible for reviewing decisions and published work.</p><h2>Learn by helping</h2><p>We want students and new graduates to develop practical AI experience, showcase contributions and build evidence of their skills. That experience may support applications for scholarships, internships or a first job; participation does not guarantee any outcome.</p><h2>An open index, community-maintained adapters</h2><p>Contributors connect regional sources through pull requests. Shared schemas make the data reusable. Today the published index is centralized; independent federated publishing is a future direction rather than a claim about the current architecture.</p></div><a class="button" href="/docs/contributing/">Find your first contribution →</a></section>`);
await page('/contributors/','The people behind the index','Public contributions to YouthOpp, with transparent scoring and GitHub attribution.',`<section class="wrap section"><p class="eyebrow">BUILT IN THE OPEN</p><h1 class="page-title">Every contribution matters.</h1><p class="lede">A public record of the people helping make opportunities easier to discover.</p><div class="source-grid">${contributors.length?contributors.sort((a,b)=>b.score-a.score||a.login.localeCompare(b.login)).map((c,i)=>`<article class="source-card"><span class="tag">#${i+1} · ${e(c.score)} contribution ${c.score===1?'point':'points'}</span><h2><a href="${e(safeUrl(c.html_url||`https://github.com/${c.login}`))}">${e(c.name||c.login)}</a></h2><p>@${e(c.login)}</p><p class="small">${e(c.commits||0)} authored non-merge commits</p></article>`).join(''):'<p>Contributor history has not been collected for this build. No rankings are invented.</p>'}</div><p class="small">History collected: ${date(contributorMeta.generated_at)} · Collection status: ${e(contributorMeta.status||'not collected')} · Mapping warnings: ${e((contributorMeta.mapping_errors||[]).length)} · Unresolved identities: ${e(contributorMeta.unresolved_commits||contributorMeta.unresolved_identities||0)}</p><p class="notice">Scores summarize recorded GitHub activity, not skill or personal value. AI-assisted activity is disclosed by the account responsible for it. <a href="/docs/contributor-scoring/">Scoring method and limitations</a>.</p></section>`);
const docsDir=path.join(root,'docs');const docFiles=(await fs.readdir(docsDir)).filter(f=>f.endsWith('.md')).sort();const docItems=[];
for(const filename of docFiles){const text=await fs.readFile(path.join(docsDir,filename),'utf8');const title=text.match(/^# (.+)$/m)?.[1]||label(filename.replace('.md','').replace(/-/g,' '));const route=`/docs/${slug(filename.replace('.md',''))}/`;docItems.push({title,route});await page(route,title,`${title}: YouthOpp project documentation.`,`<section class="wrap section narrow"><a href="/docs/" class="text-link">← Documentation</a><div class="prose">${markdown(text)}</div></section>`);}
await page('/docs/','Project documentation','Mission, architecture, source research and contribution guides for YouthOpp.',`<section class="wrap section"><p class="eyebrow">THE PROJECT, EXPLAINED</p><h1 class="page-title">Open work. Clear decisions.</h1><p class="lede">Understand the mission, explore the architecture and help improve the index.</p><div class="source-grid">${docItems.map(d=>`<a class="source-card doc-card" href="${d.route}"><h2>${e(d.title)}</h2><span>Read documentation →</span></a>`).join('')}</div></section>`);
await fs.cp(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});await fs.writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${config.url}/sitemap.xml\n`);await fs.writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${e(config.url+r)}</loc></url>`).join('')}</urlset>`);await fs.writeFile(path.join(out,'llms.txt'),`# YouthOpp\n\n${config.description}\n\nYouthOpp is a discovery index. Original publishers are the authority. Summaries preserve source language. Missing eligibility is unknown.\n\n- [Mission](${config.url}/about/)\n- [Opportunities](${config.url}/opportunities/)\n- [Sources](${config.url}/sources/)\n- [Documentation](${config.url}/docs/)\n`);await fs.writeFile(path.join(out,'.nojekyll'),'');return{routes,records:records.length,out};
}
export function markdown(text){const lines=text.split(/\r?\n/);let out=[],code=[],inCode=false,table=[];const flushTable=()=>{if(!table.length)return;const rows=table.filter(l=>!/^\s*\|?[\s:|-]+\|?\s*$/.test(l)).map(l=>l.trim().replace(/^\||\|$/g,'').split('|'));out.push('<div class="table-scroll"><table>'+rows.map((r,i)=>'<tr>'+r.map(c=>`<${i?'td':'th'}>${inline(c.trim())}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</table></div>');table=[];};for(const line of lines){if(line.startsWith('```')){flushTable();if(inCode){out.push('<pre><code>'+escapeHtml(code.join('\n'))+'</code></pre>');code=[];}inCode=!inCode;continue;}if(inCode){code.push(line);continue;}if(line.trim().startsWith('|')){table.push(line);continue;}flushTable();if(line.startsWith('### '))out.push(`<h3>${inline(line.slice(4))}</h3>`);else if(line.startsWith('## '))out.push(`<h2>${inline(line.slice(3))}</h2>`);else if(line.startsWith('# '))out.push(`<h1 class="page-title">${inline(line.slice(2))}</h1>`);else if(line.startsWith('- '))out.push(`<p class="list-item">• ${inline(line.slice(2))}</p>`);else if(line.trim())out.push(`<p>${inline(line)}</p>`);}flushTable();return out.join('\n');}
function inline(value){return escapeHtml(value).replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,title,url)=>`<a href="${escapeHtml(url.startsWith('/')?url:safeUrl(url))}">${title}</a>`).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');}
if(process.argv[1]===fileURLToPath(import.meta.url))console.log(await build());
